config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  namespace :admin do
    resources :users
    resources :products
    resources :categories
    resources :discounts
    resources :orders, only: %i[index show]
  end

  namespace :user do
    resources :products, only: [:index]
    resources :order_items, only: %i[create new destroy show]
    resources :carts, only: %i[show destroy]
    resources :orders
  end
  post 'user/orders/discount', to: 'user/orders#discount', as: 'orders_coupon'
  post 'payments/create', to: 'payments#create'
  resources :invitations, only: %i[new create]

  namespace :api do
    post :auth, to: 'authentication#create'
    namespace :admin do
      resources :users
      resources :products
    end
  end
end

app/models/order.rb
# frozen_string_literal: true

# Order model file
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  enum payment: %i[cash card]
  enum status: %i[complete pending]
  validates :firstname, :lastname, :email, :address, presence: true, on: :update
end

app/models/user.rb
# frozen_string_literal: true

# Users Model
class User < ApplicationRecord
  paginates_per 5
  attr_writer :login

  has_many :orders, dependent: :nullify
  has_one :cart, dependent: :destroy
  enum role: %i[client admin]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, authentication_keys: [:login]

  PASSWORD_FORMAT = /\A
  (?=.*[a-z])        # Must contain a lower case character
  (?=.*[A-Z])        # Must contain an upper case character
  (?=.*[[:^alnum:]]) # Must contain a symbol
/x.freeze

  validates :password,
            presence: true,
            format: { with: PASSWORD_FORMAT }, on: :create

  validates :user_name, presence: true
  validates :email, presence: true
  validates :password, confirmation: { case_sensitive: true }

  def login
    @login || user_name || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(['lower(user_name) = :value OR lower(email) = :value',
                                    { value: login.downcase }]).first
    elsif conditions.key?(:user_name) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end

  def self.search_user(search)
    User.where('cast(id as text) LIKE :value or lower(users.user_name) LIKE :value or lower(users.email) LIKE :value ',
               value: "%#{search.downcase}%")
  end
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

# User
module Admin
  # Class Orders
  class OrdersController < ApplicationController
    before_action :current_cart
    def index
      @orders = Order.all.order(firstname: :desc)
    end

    def show
      @order = Order.find(params[:id])
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

# User Controller
module Admin
  # Class User Controller
  class UsersController < ApplicationController
    before_action :find_user, only: %i[show update edit destroy]
    helper_method :sort_column, :sort_direction
    before_action :current_cart

    def index
      per_page = params[:page]
      search_param = params[:search]
      search(search_param, per_page)
      respond_to do |format|
        format.html
        format.csv { send_data ExportService::UserExport.new(User.all).to_csv, filename: "userinfo-#{Date.today}.csv" }
      end
    end

    def sort_param
      "#{sort_column} #{sort_direction}"
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to @user
      else
        render 'new'
      end
    end

    def show; end

    def update
      if @user.update(user_params)
        redirect_to([:admin, @user])
      else
        render 'edit'
      end
    end

    def edit; end

    def destroy
      @user.destroy
      redirect_to admin_users_path
    end

    private

    def search(search_param, per_page)
      @users = if search_param.present?
                 User.search_user(search_param)
                   .page(per_page)
               else
                 User.all.page(per_page).order(sort_param)
               end
      @users.page(per_page)
    end

    def find_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:user_name, :email, :password)
    end

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : 'id'
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
    end
  end
end

app/controllers/api/admin/users_controller.rb
# frozen_string_literal: true

module Api
  # User Controller
  module Admin
    # Class User Controller
    class UsersController < ApplicationController
      before_action :find_user, only: %i[show update edit destroy]
      helper_method :sort_column, :sort_direction
      before_action :current_cart

      def index
        @users = User.order(id: :desc)
      end

      def sort_param
        "#{sort_column} #{sort_direction}"
      end

      def new
        @user = User.new
      end

      def create
        @user = User.new(user_params)
        if @user.save
          redirect_to @user
        else
          render 'new'
        end
      end

      def show; end

      def update
        if @user.update(user_params)
          redirect_to([:admin, @user])
        else
          render 'edit'
        end
      end

      def edit; end

      def destroy
        @user.destroy
        redirect_to admin_users_path
      end

      private

      def search(search_param, per_page)
        @users = if search_param.present?
                   User.search_user(search_param)
                     .page(per_page)
                 else
                   User.all.page(per_page).order(sort_param)
                 end
        @users.page(per_page)
      end

      def find_user
        @user = User.find(params[:id])
      end

      def user_params
        params.require(:user).permit(:user_name, :email, :password)
      end

      def sort_column
        User.column_names.include?(params[:sort]) ? params[:sort] : 'id'
      end

      def sort_direction
        %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
      end
    end
  end
end

app/controllers/user/carts_controller.rb
# frozen_string_literal: true

# UserNamespace
class User
  # Carts
  class CartsController < ApplicationController
    before_action :current_cart, only: %i[show destroy]

    def show; end

    def destroy
      @current_cart.empty
      redirect_to user_products_path
    end
  end
end

app/controllers/user/order_items_controller.rb
# frozen_string_literal: true

# User namespace
class User
  # OrderItemsController
  class OrderItemsController < ApplicationController
    before_action :current_cart

    def create
      result = CreateOrderItem.call(
        product_id: params[:product_id],
        current_cart: @current_cart,
      )
      @order_item = result.order_item
      if result.success?
        redirect_to user_cart_path(@current_cart)
      else
        redirect_to user_products_path, alert: 'Error: Something went wrong.'
      end
    end

    def destroy
      @order_item = OrderItem.find(params[:id])
      @order_item.destroy
      redirect_to user_cart_path(@current_cart)
    end

    private

    def order_item_params
      params.require(:order_item).permit(:quantity, :product_id, :cart_id)
    end
  end
end

app/controllers/user/orders_controller.rb
# frozen_string_literal: true

# User
class User
  # Class Orders
  class OrdersController < ApplicationController
    before_action :set_order, only: %i[show]
    before_action :current_cart

    def index
      @orders = Order.order(name: :desc)
    end

    def show; end

    def new
      value = Discount.validate_coupon(params[:coupon], current_cart) if params[:coupon].present?
      @coupon = @current_cart.sub_total.to_i - value.to_i
      @order = Order.new
    end

    def create
      order = current_order
      order.price = @current_cart.sub_total
      order.update(order_params)
      @current_cart.order_items.each do |item|
        order.order_items << item
        item.cart_id = nil
        item.save
      end
      order.status = 0
      order.save
      if order.payment == 'card'
        redirect_to user_order_path(order)
      else
        redirect_to root_path
      end
    end

    private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:firstname, :lastname, :email, :address, :payment)
    end
  end
end

app/controllers/user/products_controller.rb
# frozen_string_literal: true

# Product Controller
class User
  # Class for ProductsController
  class ProductsController < ApplicationController
    before_action :current_cart
    def index
      @products = Product.order(title: :desc)
    end
  end
end

app/views/user/orders/_coupon.html.erb
<div class="container-fluid w-75 border rounded shadow mt-5 p-4 text-center mb-5">
  <h5>Apply coupon if available</h5>
  <%= form_with url: new_user_order_path, method: 'get', remote: true do |f| %>
  <div class="field mb-3 text-start">
    <%= f.label :coupon, class: "form-label" %>
    <%= f.text_field :coupon, autofocus: true, autocomplete: "title", class: "form-control" %>
  </div>
  <div class="actions mb-2">
    <%= f.submit "Apply", class: 'btn btn-primary btn-lg' %>
  </div>
  <h3>Final Total: <%= @current_cart.sub_total %></h3>

  <h3>After Discount: <%= coupon %></h3>
<% end %>
</div>

app/views/user/orders/index.html.erb
<h2>All Orders</h2>
<% @orders.each do |order| %>
  <p>Name: <%= order.firstname %></p>
  <p>Email: <%= order.email %></p>
  <p>Line Items: </p>
  <ul>
    <% order.order_items.each do |item| %>
    <li><%= item.quantity %> x <%= item.product.title %></li>
    <% end %>
  </ul>
<% end %>

app/views/user/orders/new.html.erb
<div class="container-fluid w-75 border rounded shadow mt-5 p-4 text-center mb-5">
  <h4> Customer Information</h4>
  <%= form_for [:user,@order] do |f| %>
    <div>
      <%= f.label :first_name %><br>
      <%= f.text_field :firstname, required: true, autofocus: true %>
    </div>
    <div>
      <%= f.label :last_name %><br>
      <%= f.text_field :lastname, required: true, autofocus: true %>
    </div>
    <div>
      <%= f.label :email %><br>
      <%= f.email_field :email, required: true %>
    </div>
    <div>
      <%= f.label :address %><br>
      <%= f.text_area :address, required: true %>
    </div>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Select Payment Method
    </button>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Payment Method</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="field">
              <%= f.radio_button :payment, "cash" %>
              <%= f.label :cash,"cash" %>
              <%= f.radio_button :payment, "card" %>
              <%= f.label :cash,"card" %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <div class="btn btn-primary " >
              <%= f.submit %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div id='coupon'>
  <%= render 'coupon', coupon: @coupon %>
</div>

app/views/user/orders/new.js.erb
$('#coupon').html("<%= j render partial: 'coupon', locals: {coupon: @coupon} %>");

app/views/user/orders/show.html.erb
<div class="container-fluid w-50 border rounded shadow mt-5 p-4">
  <%= link_to "Back", admin_orders_path  %>
  <h2>Order Details</h2>
  <div class="text-center">
    <% @order.order_items.each do |order_item| %>
    <h5>Order ID = <%= order_item.order_id %></h5>
      <p>Product ID = <%= order_item.product_id %></p>
      Product name = <%= order_item.product.title %></p>
      Product Description = <%= order_item.product.description %></p>
      Unit Price = <%= order_item.product.price %></p>
    <% end %>
    <p>Total Price = <%= @order.price %></p>
    <%= link_to "Pay with card", payments_create_path, params: {id: @order.id},class: "btn btn-primary btn-lg", method: :post, remote: true %>
  </div>
</div>