config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  namespace :admin do
    resources :users
    resources :products
    resources :categories
    resources :discounts
    resources :orders, only: %i[index show]
  end

  namespace :user do
    resources :products, only: [:index]
    resources :order_items, only: %i[create new destroy show]
    resources :carts, only: %i[show destroy]
    resources :orders
  end
  post 'user/orders/discount', to: 'user/orders#discount', as: 'orders_coupon'
  post 'payments/create', to: 'payments#create'
  resources :invitations, only: %i[new create]

  namespace :api do
    post :auth, to: 'authentication#create'
    namespace :admin do
      resources :users
      resources :products
    end
  end
end

app/models/order.rb
# frozen_string_literal: true

# Order model file
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  enum payment: %i[cash card]
  enum status: %i[complete pending]
  validates :firstname, :lastname, :email, :address, presence: true, on: :update
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

# User
module Admin
  # Class Orders
  class OrdersController < ApplicationController
    before_action :current_cart
    def index
      @orders = Order.all.order(firstname: :desc)
    end

    def show
      @order = Order.find(params[:id])
    end
  end
end

app/controllers/user/orders_controller.rb
# frozen_string_literal: true

# User
class User
  # Class Orders
  class OrdersController < ApplicationController
    before_action :set_order, only: %i[show]
    before_action :current_cart

    def index
      @orders = Order.order(name: :desc)
    end

    def show; end

    def new
      value = Discount.validate_coupon(params[:coupon], current_cart) if params[:coupon].present?
      @coupon = @current_cart.sub_total.to_i - value.to_i
      @order = Order.new
    end

    def create
      order = current_order
      order.price = @current_cart.sub_total
      order.update(order_params)
      @current_cart.order_items.each do |item|
        order.order_items << item
        item.cart_id = nil
        item.save
      end
      order.status = 0
      order.save
      if order.payment == 'card'
        redirect_to user_order_path(order)
      else
        redirect_to root_path
      end
    end

    private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:firstname, :lastname, :email, :address, :payment)
    end
  end
end

app/views/admin/orders/index.html.erb
<div class="container-fluid w-75 border rounded shadow mt-5 p-4 text-center sign-up-form mb-5" >
  <h2>Orders</h2>
  <div class="table-responsive">
    <table class="table table-sm">
      <thead>
          <th scope="col">ID</th>
          <th scope="col">First Name</th>
          <th scope="col">LastName</th>
          <th scope="col">Email</th>
          <th scope="col">Payment Method</th>
          <th> Action </th>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= order.firstname %></td>
          <td><%= order.lastname %></td>
          <td><%= order.email %></td>
          <td><%= order.payment %></td>
          <td><%= link_to 'Show Order', admin_order_path(order) %></td>
        </tr>
        <% end %> 
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container-fluid w-50 border rounded shadow mt-5 p-4">
  <%= link_to "Back", admin_orders_path  %>
  <h2>Order Details</h2>
  <div class="text-center">
    <% @order.order_items.each do |order_item| %>
    <h5>Order ID = <%= order_item.order_id %></h5>
      <p>Product ID = <%= order_item.product_id %></p>
      Product name = <%= order_item.product.title %></p>
      Product Description = <%= order_item.product.description %> </p>
      Unit Price = <%= order_item.product.price %></p>
    <% end %>
  </div>
</div>