config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  namespace :admin do
    resources :users
    resources :products
    resources :categories
    resources :discounts
    resources :orders, only: %i[index show]
  end

  namespace :user do
    resources :products, only: [:index]
    resources :order_items, only: %i[create new destroy show]
    resources :carts, only: %i[show destroy]
    resources :orders
  end
  post 'user/orders/discount', to: 'user/orders#discount', as: 'orders_coupon'
  post 'payments/create', to: 'payments#create'
  resources :invitations, only: %i[new create]

  namespace :api do
    post :auth, to: 'authentication#create'
    namespace :admin do
      resources :users
      resources :products
    end
  end
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">EMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100 d-flex justify-content-end align-items-center">
        <% if current_user %>
          <li>
            <%= current_user.email %>
          </li>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Invite User",new_invitation_path,  class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Users", admin_users_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Orders", admin_orders_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Products", admin_products_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Categories", admin_categories_path, class: "nav-link active" %>
            </li>
            <li class="nav-item">
              <%= link_to "Discounts", admin_discounts_path, class: "nav-link active" %>
            </li>
            <li>
              <%= link_to 'Log out', destroy_user_session_path,class: "nav-link active", method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Products', user_products_path,class: "nav-link active" %>
            </li>
            <li>
              <%= link_to 'Log out', destroy_user_session_path,class: "nav-link active", method: :delete %>
            </li>
          <% end %>
        <% else %>
          <div id="navbar">
            <ul class="nav navbar-nav pull-right">
              <li>
                <% link_to 'Home', root_path %>
              </li>
              <ul class="nav navbar-nav pull-right">
                <li>
                  <%= link_to 'Log In', new_user_session_path, class: "nav-link active" %>
                </li>
                <li>
                  <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link active" %>
                </li>
              </ul>
            </ul>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</nav>